# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI - Lint and Tests

on:
  pull_request:
    branches:
    - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Lint with Pylint
      run: |
        pip install pylint
        pylint mercadopago
        pylint --rcfile=tests/.pylintrc tests

    - name: Lint with Isort
      run: |
        pip install isort
        isort .

    - name: Test with unittest
      run: |
        python -m unittest discover tests/
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
